### ISSUE TITLE
Remove all that modules mess

### ISSUE THREAD

**Issue by Meroje** [Meroje/puppet-devbox#2]
We need a very light box, as we already have our tools, replicating them here is unnecessary.
- zsh
- oh-my-zsh
- xhrprof
- vim ? I think it is convenient for like apache config

**Comment by niallobrien** [comment]
I think you should keep vim, remove the rest.

**Comment by Meroje** [comment]
Vim will stay, svn will go instead.

**Comment by Meroje** [comment]
Pear modules have to go ! Anything to leave [here](https://github.com/Meroje/puppet-devbox/blob/master/puppet/modules/php/manifests/init.pp#L49-73) ?

**Comment by niallobrien** [comment]
I personally don't need any of those (right now).
